//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AdaptatonApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Alert
    {
        public string Id { get; set; }
        public string IncidentId { get; set; }
        public string UserId { get; set; }
        public string Photo { get; set; }
        public string Description { get; set; }
        public bool Help { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public System.DateTime UpdatedAt { get; set; }
    
        public virtual Pin Pin { get; set; }
        public virtual User User { get; set; }
    }
}
